name: 'Label PR'
description: 'Automatically labels a pull request based on title and body content'
inputs:
  repo-token:
    description: 'Token for the GitHub repository'
    required: true
  config:
    description: 'JSON configuration mapping labels to lists of regex patterns'
    required: true
runs:
  using: 'node16'
  main: 'index.js'