name: 'Wrapper action sample'
inputs:
  name:
    description: 'TBD1'
    default: 'GitHub'
  repo-token:
    description: 'Token for the GitHub repository'
    required: true
description: 'TBD'
runs:
  using: 'node12'
  main: 'main.js'
#  post: 'cleanup.js'